#!/bin/bash

set -euo pipefail

source "$(dirname "$0")/scripts/helpers.sh"

export DOCKER_CLI_HINTS=false
docker build -t lethen -f docker/Dockerfile-Bazel .
docker run --name lethen_write_baseline -t lethen scan "$@" --bazel --write-baseline /baseline.json
docker cp lethen_write_baseline:baseline.json ./baselines/linux-bazel.json
docker rm lethen_write_baseline
format_baseline baselines/linux-bazel.json
